title: MUHAMMAD IQBAL BIN SUHAIDIN
logo: github/g7 low.jpg
description: <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="large" data-theme="dark" data-type="HORIZONTAL" data-vanity="iqbal-suhaidin-560a452a8" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://my.linkedin.com/in/iqbal-suhaidin-560a452a8?trk=profile-badge">Iqbal Suhaidin</a></div>
show_downloads: false
theme: jekyll-theme-minimal
