title: MUHAMMAD IQBAL BIN SUHAIDIN
tagline: Backend Developer | Full-Stack Developer | Computer Science Graduate
logo: github/g7 low.jpg
description: |
  Computer Science graduate passionate about backend and full-stack development, 
  with proven hands-on experience in building web applications. Skilled in backend 
  development, database management, web design, and machine learning applications.
  
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="large" data-theme="dark" data-type="HORIZONTAL" data-vanity="iqbal-suhaidin-560a452a8" data-version="v1">
    <a class="badge-base__link LI-simple-link" href="https://my.linkedin.com/in/iqbal-suhaidin-560a452a8?trk=profile-badge">LinkedIn Profile</a>
  </div>

author: Muhammad Iqbal bin Suhaidin
email: iqbal22shd@gmail.com
phone: "+6019-6356149"
location: "Seri Kembangan 43300, Selangor, Malaysia"

show_downloads: false
theme: jekyll-theme-minimal

# Social media
linkedin_username: iqbal-suhaidin-560a452a8
github_username: IqbalSHD

# SEO
google_analytics: # Add your GA tracking ID if you have one
lang: en-US

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - README.md
